name: Node CI

on:
  pull_request:
    branches: [master]

jobs:
  ci:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Installing depedencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Svelte validate
        run: npm run validate
      - name: Run unit tests
        run: npm test
      - name: Build the app
        run: npm run build
      - name: Run the integration tests
        run: npx cypress run --env BASE_URL=https://svelte-minesweeper-git-${GITHUB_HEAD_REF}-shaance.vercel.app/
